name: Shell Installation Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test-shells:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        shell: ["zsh", "fish", "bash"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Zsh and Fish on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh fish

      - name: Install Zsh and Fish on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install zsh fish

      - name: Setup shell environment
        run: |
          mkdir -p ~/.config/fish
          mkdir -p ~/.zsh
          touch ~/.bashrc

      - name: Test install script in Zsh
        if: matrix.shell == 'zsh'
        run: |
          bash ./install.bash
        shell: zsh {0}
      - name: Test install script in Fish
        if: matrix.shell == 'fish'
        run: |
          bash ./install.bash
        shell: fish {0}

      - name: Verify installation
        run: |
          if [ "${{ matrix.shell }}" = "zsh" ]; then
            zsh -c "source ~/.zshrc && echo 'Zsh configuration loaded'"
          elif [ "${{ matrix.shell }}" = "fish" ]; then
            fish -c "source ~/.config/fish/config.fish && echo 'Fish configuration loaded'"
          elif [ "${{ matrix.shell }}" = "bash" ]; then
            bash -c "source ~/.bashrc && echo 'Bash configuration loaded'"
          fi
          [ -f ~/.shelltime/hooks/bash-preexec.sh ] || (echo "bash-preexec.sh not found in ~/.shelltime/hooks!" && exit 1)
          ls ~/.shelltime
          ls ~/.shelltime/bin
          ls ~/.shelltime/hooks
